name: Content Tracker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * 1-5']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
